athlete_management/urls.py
from django.contrib import admin
from django.urls import include, path, re_path
from django.conf.urls import url
from training_area.views import team, athlete, coach, app
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('training_area.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/signup/', team.SignUpView.as_view(), name = 'signup'),
    path('accounts/signup/athlete/', athlete.AthleteSignUpView.as_view(), name = 'athlete_signup'),
    path('accounts/signup/coach/', coach.CoachSignUpView.as_view(), name = 'coach_signup'),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

training_area/urls.py
from django.urls import include, path, re_path
from .views import team, athlete, coach, app

urlpatterns = [
    path('', team.home, name='home'),

    path('app/', include(([
        path('user=<int:pk>/log', app.LogView.as_view(), name='log_view'),
        path('workout=<int:workout_id>/add_comment', app.add_comment, name='add_comment'),
        path('comment=<int:comment_id>/delete_comment', app.delete_comment, name='delete_comment'),
        path('<int:notif_id>/delete_notification', app.delete_notification, name='delete_notif'),
        path('delete_all_notifications', app.delete_all_notifications, name='delete_all_notif'),
        path('user=<int:pk>/workout=<int:pk_2>', app.WorkoutDetail.as_view(), name='workout_detail'),
        path('user=<int:pk>/micro=<int:pk_2>', app.MicrocycleDetail.as_view(), name='micro_detail'),
        path('<str:slug>/profile', app.ProfileView.as_view(), name='profile_view'),
        path('search_coach', app.SearchCoachView.as_view(), name='search_coach'),
        path('<int:pk>/search_athlete', app.SearchAthleteView.as_view(), name='search_athlete'),
        path('<int:pk>/search_workout', app.SearchWorkoutView.as_view(), name='search_workout'),
        path('calendar', app.CalendarView.as_view(), name='calendar'),
        path('calendar/new_event', app.event, name='event_new'),
        path('calendar/event=<int:event_id>', app.event, name='event_edit'),
        path('calendar/delete/event=<int:event_id>', app.delete_event, name='event_delete'),
        path('user=<int:pk>/chart_type=<str:chart_type>', app.RPEView.as_view(), name='view_rpe'),
        #######
        path('analytics', app.ChartView.as_view(), name='analytics'),
        path('api/chartdata', app.ChartData.as_view(), name ='testdata'),
        path('testviews/api/chartdata', app.ChartData.as_view(), name ='testdata'),
        path('api/data', app.get_data, name='api-data'),
        path('ajax/load-lifts/', app.load_lifts, name = 'ajax_load_lifts'),
        path('ajax/display-metrics/', app.display_metrics, name = 'ajax_display_metrics'),
        path('ajax/load-meso/', app.load_meso, name = 'ajax_load_meso'),
        path('ajax/testpost/', app.testpost, name = 'ajax_test_post'),
        #####
        path('ajax/validate_kg/', app.validate_kg, name = 'ajax_validate_kg'),
        path('ajax/validate_num_reps/', app.validate_num_reps, name = 'ajax_validate_num_reps'),
        path('ajax/validate_rpe/', app.validate_rpe, name = 'ajax_validate_rpe'),
        path('ajax/validate_movement_name/', app.validate_movement_name, name = 'ajax_validate_movement_name'),
        path('ajax/validate_percentage/', app.validate_percentage, name = 'ajax_validate_percentage'),
        path('ajax/validate_rm/', app.validate_rm, name = 'ajax_validate_rm'),
        path('ajax/validate_checked/', app.validate_checked, name = 'ajax_validate_checked'),
        path('ajax/validate_workout_name/', app.validate_workout_name, name = 'ajax_validate_workout_name'),
        path('ajax/validate_description/', app.validate_description, name = 'ajax_validate_description'),
        path('ajax/validate_movement_group_name/', app.validate_movement_group_name, name = 'ajax_validate_movement_group_name'),
        path('ajax/validate_mesocycle_name/', app.validate_mesocycle_name, name = 'ajax_validate_mesocycle_name'),

    ], 'training_area'), namespace='app')),

    path('athlete/', include(([
        path('edit/<int:workout_id>', athlete.edit_workout, name = 'edit_workout'),
    	path('search_coach/', athlete.SearchCoachView.as_view(), name='search_coach'),
        path('dashboard/', athlete.DashboardView.as_view(), name='dashboard'),
        #path('<str:slug>/', athlete.AthleteDetailView.as_view(), name = 'athlete_detail'),
        path('add_coach/<int:coach_id>/', athlete.add_coach, name = 'add_coach'),
        path('remove_coach/<int:coach_id>/', athlete.remove_coach, name = 'remove_coach'),
        path('program_view/<int:pk>/', athlete.ProgramDetailView.as_view(), name = 'program_view'),
        path('<int:movement_id>/edit', athlete.edit_movement, name = 'edit_movement'),
        path('<int:movement_id>/gen_backoff', athlete.gen_backoff, name = 'generate_backoff'),
        path('submit/<int:workout_id>', athlete.submit_workout, name = 'submit'),
        path('ajax/submit_fatigue/', athlete.submit_fatigue, name = 'ajax_submit_fatigue'),
        path('ajax/accessory_load_done/', athlete.accessory_load_done, name = 'ajax_accessory_load_done'),
        path('ajax/accessory_protocol_done/', athlete.accessory_protocol_done, name = 'ajax_accessory_protocol_done'),

    ], 'training_area'), namespace='athlete')),

    path('coach/', include(([
        path('delete_workout/<int:athlete_id>/<int:workout_id>', coach.WorkoutDeleteView.as_view(), name = 'delete_workout'),
        path('delete_micro/<int:athlete_id>/<int:microcycle_id>', coach.MicrocycleDeleteView.as_view(), name = 'delete_micro'),
        path('delete_meso/<int:athlete_id>/<int:mesocycle_id>', coach.MesocycleDeleteView.as_view(), name = 'delete_meso'),
        path('dashboard/', coach.DashboardView.as_view(), name='dashboard'),
        path('<str:slug>/', coach.CoachDetailView.as_view(), name = 'coach_detail'),
        path('athlete=<int:pk>/add_workout', coach.AddWorkoutView.as_view(), name = 'add_workout'),
        path('<int:microcycle_id>/edit_micro_name', coach.edit_micro_name, name = 'edit_micro_name'),
        path('duplicate/<int:movement_id>', coach.duplicate, name = 'duplicate'),
        path('duplicate_micro/<int:microcycle_id>', coach.duplicate_microcycle, name = 'duplicate_micro'),
        path('delete/<int:movement_id>', coach.delete_movement, name = 'delete'),
        path('editrm/<int:rep_max_id>', coach.edit_rep_max, name = 'edit_rep_max'),
        path('deleterm/<int:rep_max_id>', coach.delete_rep_max, name = 'delete_rep_max'),
        path('edit/<int:workout_id>', coach.edit_workout, name = 'edit_workout'),
        path('edit_profile/<int:pk>', coach.UpdateCoach.as_view(), name = 'edit_profile'),
        path('athlete=<int:pk>/create_micro', coach.CreateMicrocycleView.as_view(), name = 'create_micro'),
        path('athlete=<int:pk>/create_meso', coach.CreateMesocycleView.as_view(), name = 'create_meso'),
        path('athlete=<int:athlete_id>/micro=<int:pk_2>/add', coach.add_wo_to_micro, name = 'add_wo_to_micro'),
        path('athlete=<int:athlete_id>/meso=<int:pk_2>/add', coach.add_micro_to_meso, name = 'add_micro_to_meso'),
        path('<int:movement_id>/quick_edit', coach.edit_movement_quick, name = 'edit_movement_quick'),
        path('<int:athlete_id>/add_rep_max', coach.add_rep_max, name = 'add_rep_max'),
        path('athlete=<int:pk>/workout=<int:pk_2>/add_movement_test', coach.AddMovementViewTest.as_view(), name = 'add_movement_test'),

        path('ajax/remove_athlete/', coach.remove_athlete, name = 'ajax_remove_athlete'),
        path('ajax/add_accessory/', coach.add_accessory, name = 'ajax_add_accessory'),
        path('ajax/add_movement/', coach.add_movement, name = 'ajax_add_movement'),
        path('ajax/delete_accessory/', coach.delete_accessory, name = 'ajax_delete_accessory'),
        path('ajax/delete_microcycle/', coach.delete_microcycle, name = 'ajax_delete_microcycle'),
        path('ajax/remove_workout/', coach.remove_workout, name = 'ajax_remove_workout'),
        path('ajax/duplicate_movement/', coach.duplicate_movement, name = 'ajax_duplicate_movement'),
        path('ajax/fast_delete_movement/', coach.fast_delete_movement, name = 'ajax_fast_delete_movement'),
    ], 'training_area'), namespace='coach')),
    #re_path(r'^coach/(?P<user>[\w-]+)/$', coach.CoachDetailView.as_view(), name = 'coach_detail'),
]

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="{% static 'css/bulma.css' %}">
    {% if user.is_authenticated and user.is_teacher %}
      <link rel="stylesheet" type="text/css" href="{% static 'css/bulma.css' %}">
    {% else %}
      <link rel="stylesheet" type="text/css" href="{% static 'css/bulma.css' %}">
    {% endif %}
  </head>
  <body>
    <div class="container my-4">
      <div class="row justify-content-center">
        <div class="col-md-10 col-sm-12">
          <div class="row">
            <div class="col-6">
              <h1 class="logo">
                <a href="{% url 'home' %}">
                  Django School
                  {% if user.is_authenticated %}
                    {% if user.is_teacher %}
                      <span class="icon-feather" data-toggle="tooltip" data-placement="right" title="Teacher profile"></span>
                    {% else %}
                      <span class="icon-graduation-cap" data-toggle="tooltip" data-placement="right" title="Student profile"></span>
                    {% endif %}
                  {% endif %}
                </a>
              </h1>
            </div>
            <div class="col-6 text-right">
              {% if user.is_authenticated %}
                <p class="pt-3">Logged in as <strong>{{ user.username }}</strong>. <a href="{% url 'logout' %}">Log out</a>.</p>
              {% else %}
                <a href="{% url 'login' %}" class="btn btn-light" role="button">Log in</a>
                <a href="{% url 'signup' %}" class="btn btn-primary" role="button">Sign up</a>
              {% endif %}
            </div>
          </div>
          <div class="card mb-3">
            <div class="card-body">
              {% for message in messages %}
                <div class="alert {{ message.tags }} alert-dismissible fade show" role="alert">
                  {{ message }}
                  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                  </button>
                </div>
              {% endfor %}
              {% block content %}
              {% endblock %}
            </div>
          </div>
          <footer>
          </footer>
        </div>
      </div>
    </div>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script type="text/javascript">
      $(function () {
        $('[data-toggle="tooltip"]').tooltip();
      })
    </script>
  </body>
</html>

templates/home.html
{% load static %}
<!DOCTYPE html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>AGOGE</title>
    <link rel="stylesheet" type="text/css" href="{% static 'bulma/css/landing.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'bulma/css/style.css' %}">

  </head>
</html>

<body>

  <section class="hero is-dark is-fullheight">
    <div class="hero-head">
    <header class="navbar is-dark">
      <div class="container">
        <div class="navbar-brand">
          <a class="navbar-item">
          </a>
          <span class="navbar-burger burger has-background-info" data-target="navbarMenuHeroC" onclick="document.querySelector('.navbar-menu').classList.toggle('is-active');">
            <span></span>
            <span></span>
            <span></span>
          </span>
        </div>
        <div id="navbarBasicExample" class="navbar-menu">
          <div class="navbar-end">
            <a class="navbar-item" href="{% url 'login' %}">
              <strong>Log In</strong>
            </a>
            <a class="navbar-item" href="{% url 'signup' %}">
              <strong>Sign Up</strong>
            </a>
            <!--<a class="navbar-item">

            </a>
            <span class="navbar-item">
              <a class="button is-success is-inverted">
                <span class="icon">
                  <i class="fab fa-github"></i>
                </span>
                <span>Download</span>
              </a>
            </span>-->
          </div>
        </div>
        </div>

    </header>
  </div>


  </section>
</body>

templates/navbar.html
{% load static %}


{% block js %}
  <script src="{% static 'js/app.js' %}"></script>
  <script src="{% static 'js/jquery-3.3.1.js' %}"></script>
  <script src='https://cdn.jsdelivr.net/npm/chart.js@2.8.0/dist/Chart.min.js'></script>
{% endblock %}
<script>
    $(document).ready(function() {
        // messages timeout for 10 sec
        setTimeout(function() {
            $('.notification').fadeOut('slow');
        }, 3000); // <-- time in milliseconds, 1000 =  1 sec

        // delete message
        $('.del-msg').live('click',function(){
            $('.del-msg').parent().attr('style', 'display:none;');
        })
    });
</script>

<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>AGOGE</title>
    <!--<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.4/css/bulma.min.css">-->
    <link rel="stylesheet" type="text/css" href="{% static 'bulma/css/style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'bulma/css/font-awesome.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'bulma/css/style.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'font-awesome/css/all.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'font-awesome/css/fontawesome.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'font-awesome/css/solid.css' %}">
 </head>


<nav class="navbar is-dark" role="navigation" aria-label="main navigation">
  <div class="navbar-brand">

    {% if request.user.is_authenticated and request.user.is_coach %}
      <a class="navbar-item brand-text" href="{% url 'coach:dashboard' %}"><img src="{% static 'images/bitmap.png'%}" alt="Agoge"></a>
      {% else %}
      <a class="navbar-item brand-text" href="{% url 'athlete:dashboard' %}"><img src="{% static 'images/bitmap.png'%}" alt="Agoge"></a>
        {% endif %}
      </a>



    <div role="button " class="navbar-burger burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample" onclick="document.querySelector('.navbar-menu').classList.toggle('is-active');">
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>

    </div>
  </div>


  <div id="navbarBasicExample" class="navbar-menu is-hoverable">
    <div class="navbar-start">


      <a href="{% url 'app:view_rpe' pk=request.user.id chart_type='RTS' %}" class="navbar-item">
        RPE Chart
      </a>

      <div class="navbar-item has-dropdown is-hoverable " >
        <a class="navbar-link">
          More
        </a>

        <div class="navbar-dropdown">
          <a href="{% url 'app:calendar' %}" class="navbar-item">
            Your Calendar
          </a>
          {% if request.user.is_authenticated and request.user.is_coach %}
          <a class="navbar-item">
            <a href="{% url 'app:analytics' %}" class="navbar-item">
            Analytics
          </a>
          {% endif %}
          <!--<a class="navbar-item">
            Contact
          </a>
          <hr class="navbar-divider">
          <a class="navbar-item">
            Report an issue
          </a>-->
        </div>
      </div>
    </div>

    <div class="navbar-item">
      {% if request.user.is_authenticated and request.user.is_athlete %}
      <form method = "GET" action="{% url 'app:search_coach' %}">
      <div class="field has-addons">
        <div class="control">
          <input name="search_box" class="input" type="text"  placeholder="Find a Coach">
        </div>
        <div class="control">
          <button class="button is-info" type = "submit">
            Search
          </button>


        </div>
      </div>
        </form>
        {% else %}
        <form method = "GET" action="{% url 'app:search_athlete' request.user.id %}">
          <div class="field has-addons">
            <div class="control">
              <input name="search_box" class="input" type="text" name="search_box" placeholder="Find an Athlete">
            </div>
          <div class="control">
          <button class="button is-info" type = "submit">
            Search
          </button>
          </div>
        </div>
        </form>


        {% endif %}

      </div>

    <div class="navbar-end">
      <div class="navbar-item">
        <div class="buttons">
          {% if user.is_authenticated %}
            <a href="{% url 'logout' %}" class="button is-danger">
              <strong>Logout</strong>
            </a>
          {% else %}
            <a class="button is-light">
              Log in
            </a>
          {% endif %}
        </div>
      </div>
    </div>
  </div>


</nav>
{% for message in messages %}
  <div class="container" style="width:100%;z-index:99999;position:fixed;pointer-events:none;display:flex;flex-direction:column;padding:15px;top:0;left:0;right:0;text-align:center;align-items:center;">
    <div class="notification server-messages is-{{message.tags}}" style="width:auto;pointer-events:auto;display:inline-flex;opacity:1;">
        {{ message }}
        <a href="#" class="del-msg">&times;</a>
    </div>
  </div>
{% endfor %}
<div id="site-wrapper" class="has-background-dark">
        {% block content %}
            if you see this, something is wrong!
        {% endblock content %}
        <script>
          $(document).ready(function(){
            {% block jquery %}{% endblock %}
          })
        </script>
    </div>
</html>