athlete_management/urls.py
from django.contrib import admin
from django.urls import include, path, re_path
from django.conf.urls import url
from training_area.views import team, athlete, coach, app
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('training_area.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/signup/', team.SignUpView.as_view(), name = 'signup'),
    path('accounts/signup/athlete/', athlete.AthleteSignUpView.as_view(), name = 'athlete_signup'),
    path('accounts/signup/coach/', coach.CoachSignUpView.as_view(), name = 'coach_signup'),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

training_area/urls.py
from django.urls import include, path, re_path
from .views import team, athlete, coach, app

urlpatterns = [
    path('', team.home, name='home'),

    path('app/', include(([
        path('user=<int:pk>/log', app.LogView.as_view(), name='log_view'),
        path('workout=<int:workout_id>/add_comment', app.add_comment, name='add_comment'),
        path('comment=<int:comment_id>/delete_comment', app.delete_comment, name='delete_comment'),
        path('<int:notif_id>/delete_notification', app.delete_notification, name='delete_notif'),
        path('delete_all_notifications', app.delete_all_notifications, name='delete_all_notif'),
        path('user=<int:pk>/workout=<int:pk_2>', app.WorkoutDetail.as_view(), name='workout_detail'),
        path('user=<int:pk>/micro=<int:pk_2>', app.MicrocycleDetail.as_view(), name='micro_detail'),
        path('<str:slug>/profile', app.ProfileView.as_view(), name='profile_view'),
        path('search_coach', app.SearchCoachView.as_view(), name='search_coach'),
        path('<int:pk>/search_athlete', app.SearchAthleteView.as_view(), name='search_athlete'),
        path('<int:pk>/search_workout', app.SearchWorkoutView.as_view(), name='search_workout'),
        path('calendar', app.CalendarView.as_view(), name='calendar'),
        path('calendar/new_event', app.event, name='event_new'),
        path('calendar/event=<int:event_id>', app.event, name='event_edit'),
        path('calendar/delete/event=<int:event_id>', app.delete_event, name='event_delete'),
        path('user=<int:pk>/chart_type=<str:chart_type>', app.RPEView.as_view(), name='view_rpe'),
        #######
        path('analytics', app.ChartView.as_view(), name='analytics'),
        path('api/chartdata', app.ChartData.as_view(), name ='testdata'),
        path('testviews/api/chartdata', app.ChartData.as_view(), name ='testdata'),
        path('api/data', app.get_data, name='api-data'),
        path('ajax/load-lifts/', app.load_lifts, name = 'ajax_load_lifts'),
        path('ajax/display-metrics/', app.display_metrics, name = 'ajax_display_metrics'),
        path('ajax/load-meso/', app.load_meso, name = 'ajax_load_meso'),
        path('ajax/testpost/', app.testpost, name = 'ajax_test_post'),
        #####
        path('ajax/validate_kg/', app.validate_kg, name = 'ajax_validate_kg'),
        path('ajax/validate_num_reps/', app.validate_num_reps, name = 'ajax_validate_num_reps'),
        path('ajax/validate_rpe/', app.validate_rpe, name = 'ajax_validate_rpe'),
        path('ajax/validate_movement_name/', app.validate_movement_name, name = 'ajax_validate_movement_name'),
        path('ajax/validate_percentage/', app.validate_percentage, name = 'ajax_validate_percentage'),
        path('ajax/validate_rm/', app.validate_rm, name = 'ajax_validate_rm'),
        path('ajax/validate_checked/', app.validate_checked, name = 'ajax_validate_checked'),
        path('ajax/validate_workout_name/', app.validate_workout_name, name = 'ajax_validate_workout_name'),
        path('ajax/validate_description/', app.validate_description, name = 'ajax_validate_description'),
        path('ajax/validate_movement_group_name/', app.validate_movement_group_name, name = 'ajax_validate_movement_group_name'),
        path('ajax/validate_mesocycle_name/', app.validate_mesocycle_name, name = 'ajax_validate_mesocycle_name'),

    ], 'training_area'), namespace='app')),

    path('athlete/', include(([
        path('edit/<int:workout_id>', athlete.edit_workout, name = 'edit_workout'),
    	path('search_coach/', athlete.SearchCoachView.as_view(), name='search_coach'),
        path('dashboard/', athlete.DashboardView.as_view(), name='dashboard'),
        #path('<str:slug>/', athlete.AthleteDetailView.as_view(), name = 'athlete_detail'),
        path('add_coach/<int:coach_id>/', athlete.add_coach, name = 'add_coach'),
        path('remove_coach/<int:coach_id>/', athlete.remove_coach, name = 'remove_coach'),
        path('program_view/<int:pk>/', athlete.ProgramDetailView.as_view(), name = 'program_view'),
        path('<int:movement_id>/edit', athlete.edit_movement, name = 'edit_movement'),
        path('<int:movement_id>/gen_backoff', athlete.gen_backoff, name = 'generate_backoff'),
        path('submit/<int:workout_id>', athlete.submit_workout, name = 'submit'),
        path('ajax/submit_fatigue/', athlete.submit_fatigue, name = 'ajax_submit_fatigue'),
        path('ajax/accessory_load_done/', athlete.accessory_load_done, name = 'ajax_accessory_load_done'),
        path('ajax/accessory_protocol_done/', athlete.accessory_protocol_done, name = 'ajax_accessory_protocol_done'),

    ], 'training_area'), namespace='athlete')),

    path('coach/', include(([
        path('delete_workout/<int:athlete_id>/<int:workout_id>', coach.WorkoutDeleteView.as_view(), name = 'delete_workout'),
        path('delete_micro/<int:athlete_id>/<int:microcycle_id>', coach.MicrocycleDeleteView.as_view(), name = 'delete_micro'),
        path('delete_meso/<int:athlete_id>/<int:mesocycle_id>', coach.MesocycleDeleteView.as_view(), name = 'delete_meso'),
        path('dashboard/', coach.DashboardView.as_view(), name='dashboard'),
        path('<str:slug>/', coach.CoachDetailView.as_view(), name = 'coach_detail'),
        path('athlete=<int:pk>/add_workout', coach.AddWorkoutView.as_view(), name = 'add_workout'),
        path('<int:microcycle_id>/edit_micro_name', coach.edit_micro_name, name = 'edit_micro_name'),
        path('duplicate/<int:movement_id>', coach.duplicate, name = 'duplicate'),
        path('duplicate_micro/<int:microcycle_id>', coach.duplicate_microcycle, name = 'duplicate_micro'),
        path('delete/<int:movement_id>', coach.delete_movement, name = 'delete'),
        path('editrm/<int:rep_max_id>', coach.edit_rep_max, name = 'edit_rep_max'),
        path('deleterm/<int:rep_max_id>', coach.delete_rep_max, name = 'delete_rep_max'),
        path('edit/<int:workout_id>', coach.edit_workout, name = 'edit_workout'),
        path('edit_profile/<int:pk>', coach.UpdateCoach.as_view(), name = 'edit_profile'),
        path('athlete=<int:pk>/create_micro', coach.CreateMicrocycleView.as_view(), name = 'create_micro'),
        path('athlete=<int:pk>/create_meso', coach.CreateMesocycleView.as_view(), name = 'create_meso'),
        path('athlete=<int:athlete_id>/micro=<int:pk_2>/add', coach.add_wo_to_micro, name = 'add_wo_to_micro'),
        path('athlete=<int:athlete_id>/meso=<int:pk_2>/add', coach.add_micro_to_meso, name = 'add_micro_to_meso'),
        path('<int:movement_id>/quick_edit', coach.edit_movement_quick, name = 'edit_movement_quick'),
        path('<int:athlete_id>/add_rep_max', coach.add_rep_max, name = 'add_rep_max'),
        path('athlete=<int:pk>/workout=<int:pk_2>/add_movement_test', coach.AddMovementViewTest.as_view(), name = 'add_movement_test'),

        path('ajax/remove_athlete/', coach.remove_athlete, name = 'ajax_remove_athlete'),
        path('ajax/add_accessory/', coach.add_accessory, name = 'ajax_add_accessory'),
        path('ajax/add_movement/', coach.add_movement, name = 'ajax_add_movement'),
        path('ajax/delete_accessory/', coach.delete_accessory, name = 'ajax_delete_accessory'),
        path('ajax/delete_microcycle/', coach.delete_microcycle, name = 'ajax_delete_microcycle'),
        path('ajax/remove_workout/', coach.remove_workout, name = 'ajax_remove_workout'),
        path('ajax/duplicate_movement/', coach.duplicate_movement, name = 'ajax_duplicate_movement'),
        path('ajax/fast_delete_movement/', coach.fast_delete_movement, name = 'ajax_fast_delete_movement'),
    ], 'training_area'), namespace='coach')),
    #re_path(r'^coach/(?P<user>[\w-]+)/$', coach.CoachDetailView.as_view(), name = 'coach_detail'),
]

training_area/views/athlete.py
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.contrib.auth import login
from django.shortcuts import get_object_or_404, redirect, render
from django.utils.decorators import method_decorator
from django.views.generic import CreateView, ListView, UpdateView, DetailView
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib import messages
from django.urls import reverse
from django.forms import formset_factory, inlineformset_factory
from decimal import *
from datetime import datetime, timedelta
from django.db.models import Q

from ..decorators import athlete_required
from ..forms import AthleteSignUpForm, WorkoutForm, EditMovementFormAthlete
from ..models import User, Coach, Athlete, Macrocycle, Mesocycle, Microcycle, Workout, Movement, ExertionPerceived, Event, Notifications, Comment, Accessory

class AthleteSignUpView(CreateView):
	model = User
	form_class = AthleteSignUpForm
	template_name = 'registration/signup_form.html'

	def get_context_data(self, **kwargs):
		kwargs['user_type'] = 'Athlete'
		return super().get_context_data(**kwargs)

	def form_valid(self, form):
		user = form.save()
		login(self.request, user)
		return redirect('login')


@method_decorator([login_required, athlete_required], name='dispatch')
class DashboardView(ListView):
	model = Workout
	context_object_name = 'all_workouts'
	template_name = 'training_area/athlete/dashboard.html'

	def get_queryset(self):
		return Workout.objects.filter(athlete__user=self.request.user).order_by('completed', '-created_at')[:10]

	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		calendar = {}
		today = datetime.now() + timedelta(days=-1)

		x=today
		in_thirty_days = today + timedelta(days=30)
		#print(in_thirty_days)
		events = Event.objects.filter(start_time__gte=today, end_time__lte=in_thirty_days)
		if events:
			if self.request.user.athlete.coach:
				events=events.filter(Q(user=self.request.user) | Q(user=self.request.user.athlete.coach.user))
			else:
				events=events.filter(Q(user=self.request.user))
			for item in events:
				calendar[item.title]=[item.start_time, item.end_time]
			context['calendar'] = calendar
		notifications = Notifications.objects.filter(reciever=self.request.user)
		context['notif'] = notifications

		return context


class SearchCoachView(ListView):
	model = Coach
	context_object_name = 'available_coaches'
	queryset = Coach.objects.all()
	template_name = 'training_area/athlete/search_coach.html'

class AthleteDetailView(DetailView):
	model = Athlete
	template_name = 'training_area/athlete/athlete_detail.html'
	slug_field = 'user__username'
	#program here
class ProgramDetailView(DetailView):
	model = Macrocycle
	template_name = 'training_area/athlete/program_view.html'

@login_required
@athlete_required
def add_coach(request, coach_id):
	coach = get_object_or_404(Coach, pk=coach_id)
	athlete = Athlete.objects.get(user=request.user)
	athlete.coach = coach
	athlete.save()
	messages.success(request, "Coach Added!")
	return HttpResponseRedirect(reverse('athlete:dashboard'))

@login_required
@athlete_required
def remove_coach(request, coach_id):
	coach = get_object_or_404(Coach, pk = coach_id)
	athlete = Athlete.objects.get(user=request.user)
	athlete.coach = None
	athlete.workout_athlete.clear()
	athlete.save()
	messages.success(request, "Coach Removed!")
	return HttpResponseRedirect(reverse('athlete:dashboard'))

@login_required
@athlete_required
def edit_workout(request, workout_id):
    workout = get_object_or_404(Workout, pk=workout_id)
    MovementFormSet = inlineformset_factory(
        Workout,
        Movement,
        form = EditMovementFormAthlete,
        fields=( 'kg', 'kg_done', 'num_reps_done', 'rpe'),
        can_delete=False,
        extra=0
    )
    if request.method == 'POST':

        form = WorkoutForm(request.POST, instance=workout)
        formset=MovementFormSet(request.POST, request.FILES, instance=workout)
        #print(form.errors)
        if formset.is_valid() and form.is_valid():
            form.save()
            formset.save()
            messages.success(request, 'Workout Changed!')
            return redirect('app:workout_detail', workout.athlete.pk, workout.pk)
    else:
        #form = WorkoutForm(instance=workout)

        formset=MovementFormSet(instance=workout)

    return render(request, 'training_area/athlete/workout_edit_form.html', {
        'formset': formset
    })

@login_required
@athlete_required
def edit_movement(request, movement_id):
	movement = get_object_or_404(Movement, pk=movement_id)
	if request.POST:
		form = EditMovementFormAthlete(request.POST, instance=movement)
		if form.is_valid():
			form.save()
			messages.success(request, 'Movement Changed!')
			return redirect('app:workout_detail', movement.workout.athlete.pk, movement.workout.pk)
		else:
			for field in form:
				#print(field.errors)
				for error in field.errors:
					if 'equal to 10' in error:
						error += " RPE"
					messages.warning(request, error)

			return redirect('app:workout_detail', movement.workout.athlete.pk, movement.workout.pk)
@login_required
@athlete_required
def gen_backoff(request, movement_id):
	movement = get_object_or_404(Movement, pk=movement_id)
	print(movement)
	workout = movement.workout
	if request.POST:
		exertion = ExertionPerceived.objects.filter(rep_scale=movement.num_reps, exertion_scale=movement.rpe) #gives the object
		if not exertion:
			messages.warning(request, "RPE invalid!")
			return redirect('app:workout_detail', movement.workout.athlete.pk, movement.workout.pk)
		else:
			exertion = exertion[0]
		load_percent = exertion.percent
		if movement.kg_done == None:
			messages.warning(request, "No load done!")
			return redirect('app:workout_detail', movement.workout.athlete.pk, movement.workout.pk)
		daily_rm = movement.kg_done / load_percent
		backoff_movements = Movement.objects.filter(workout=workout, is_backoff=True, movement_name=movement.movement_name) #queryset
		if not backoff_movements:
			messages.warning(request, "No backoffs ticked!")
			return redirect('app:workout_detail', movement.workout.athlete.pk, movement.workout.pk)
		for backoff in backoff_movements: #update all objects
			backoff.kg = round((daily_rm * (backoff.percentage/Decimal(100)))/Decimal(2.5)) * Decimal(2.5)
			backoff.save()
		messages.success(request, "Backoff generated!")
		return redirect('app:workout_detail', movement.workout.athlete.pk, movement.workout.pk)
	else:
		messages.error(request, "Oops, something went wrong!")

@login_required
@athlete_required
def submit_workout(request, workout_id):
	workout = get_object_or_404(Workout, pk=workout_id)
	for movement in workout.work.all():
		if not movement.num_reps_done:
			movement.num_reps_done = movement.num_reps
			movement.save()
		if not movement.kg_done:
			movement.kg_done = movement.kg
			movement.save()
		if not movement.rpe:
			messages.warning(request, "Fill in all your RPEs")
			return redirect('app:workout_detail', workout.athlete.pk, workout.pk)
	if workout.completed == False:
		workout.completed = True
	else:
		workout.completed = False
	workout.save()
	if workout.microcycle:
		uncompleted = workout.microcycle.micro.all().filter(completed=False)
		#print(uncompleted)
		if not uncompleted:
			message = workout.athlete.user.username + " has completed " + workout.microcycle.get_html_url
			notification = Notifications(title=message, sender=workout.athlete.user, reciever=workout.athlete.coach.user)
			notification.save()
	return redirect('app:workout_detail', workout.athlete.pk, workout.pk)

def submit_fatigue(request):
	multiplier = {
		0: 1.12,
		1: 1.1,
		2: 1.07,
		3: 1.05,
		4: 1.02,
		5: 1,
		6: 0.97,
		7: 0.95,
		8: 0.92,
		9: 0.9,
		10: 0.88
	}
	workout_pk = request.POST.get('pk')
	fatigue_rating = request.POST.get('fatigue')

	workout_of_interest = get_object_or_404(Workout, pk=workout_pk)
	old_rating = workout_of_interest.fatigue_rating
	workout_of_interest.fatigue_rating = fatigue_rating
	for movement in workout_of_interest.work.all():
		if movement.kg:
			movement.kg = round(movement.kg / Decimal(multiplier[int(old_rating)]) * Decimal(multiplier[int(fatigue_rating)])/Decimal(2.5))* Decimal(2.5)
		elif movement.percentage:
			movement.percentage = Decimal(movement.percentage) / Decimal(multiplier[int(old_rating)]) * Decimal(multiplier[int(fatigue_rating)])
		movement.save()
	workout_of_interest.save()
	data = {
		"lol": "lol"
	}
	return JsonResponse(data)

def accessory_load_done(request):
	pk = request.POST.get('pk')
	load_done = request.POST.get('load_done')

	accessory = get_object_or_404(Accessory, pk=pk)
	accessory.load_done = load_done
	accessory.save()
	data = {
		"lol": "lol"
	}
	return JsonResponse(data)

def accessory_protocol_done(request):
	pk = request.POST.get('pk')
	prot_done = request.POST.get('prot_done')

	accessory = get_object_or_404(Accessory, pk=pk)
	accessory.measurement_done = prot_done
	accessory.save()
	data = {
		"lol": "lol"
	}
	return JsonResponse(data)

training_area/templates/training_area/coach/add_micro_to_meso.html
 {% extends 'navbar.html' %}
 {% load bulma_tags %}

 {% block content %}
 <div class="container section">
 <div class="column is-half is-offset-one-quarter">
 <div class="card">
 <header class="card-header">
 	<p class="card-header-title is-centered">
      Add Microcycles to Block
    </p>
 </header>
  <div class="card-content">
    <div class="content">
		<form method="post" novalidate>
        {% csrf_token %}
        {{ form|bulma }}
        <button type="submit" class="button is-success"><i class="fas fa-check"></i>Save</button>
        <a href="{% url 'coach:dashboard' %}" class="button is-light" role="button">Nevermind</a>
    	</form>
    </div>
  </div>


</div>
</div>
</div>
{% endblock %}

training_area/templates/training_area/coach/add_rep_max.html
{% extends 'navbar.html' %}
 {% load bulma_tags %}

 {% block content %}
 <div class="container section">
 <div class="column is-half is-offset-one-quarter">
 <div class="box">
 <h2 class="mb-3">Add a new RM</h2>
  <div class="row">
    <div class="col-md-6 col-sm-8 col-12">
      <form method="post" novalidate>
        {% csrf_token %}
        <div class="field">
          <div class="control">
            {{ form.rep_max_name|bulma }}
          </div>
        </div>
        <div class="field is-horizontal">

          <div class="control is-expanded">
            {{ form.rep_max|bulma }}
          </div>

        </div>
        <div class="form-row">
        <button type="submit" class="button is-success"><i class="fas fa-check"></i>Save</button>
        <a href="{% url 'app:profile_view' athlete.user %}" class="button is-light" role="button">Nevermind</a>
      </form>
    </div>
  </div>
  </div>
</div>
</div>
  {% endblock %}

training_area/templates/training_area/coach/add_wo_to_micro.html
 {% extends 'navbar.html' %}
 {% load bulma_tags %}

 {% block content %}
 <div class="container section">
 <div class="column is-half is-offset-one-quarter">
 <div class="card">
 <header class="card-header">
 	<p class="card-header-title is-centered">
      Populate Microcycle
    </p>
 </header>
  <div class="card-content">
    <div class="content">
		<form method="post" novalidate>
        {% csrf_token %}
        {{ form|bulma }}
        <button type="submit" class="button is-success"><i class="fas fa-check"></i>Save</button>
        <a href="{% url 'coach:dashboard' %}" class="button is-light" role="button">Nevermind</a>
    	</form>
    </div>
  </div>


</div>
</div>
</div>
{% endblock %}

training_area/templates/training_area/coach/create_meso_form.html
 {% extends 'navbar.html' %}
 {% load bulma_tags %}

 {% block content %}
 <div class="container section">
 <div class="column is-half is-offset-one-quarter">
 <div class="box">
 <h2 class="mb-3">Create Block</h2>
  <div class="row">
    <div class="col-md-6 col-sm-8 col-12">
      <form method="post" novalidate>
        {% csrf_token %}
        {{ form|bulma }}
        
        <button type="submit" class="button is-success"><i class="fas fa-check"></i>Save</button>
        <a href="{% url 'coach:dashboard' %}" class="button is-light" role="button">Nevermind</a>
        
      </form>
    </div>
  </div>
</div>
</div>
</div>
  {% endblock %}

training_area/templates/training_area/coach/create_micro_form.html
 {% extends 'navbar.html' %}
 {% load bulma_tags %}

 {% block content %}
 <div class="container section">
 <div class="column is-half is-offset-one-quarter">
 <div class="box">
 <h2 class="mb-3">Create Microcycle</h2>
  <div class="row">
    <div class="col-md-6 col-sm-8 col-12">
      <form method="post" novalidate>
        {% csrf_token %}
        {{ form|bulma }}
        
        <button type="submit" class="button is-success"><i class="fas fa-check"></i>Save</button>
        <a href="{% url 'coach:dashboard' %}" class="button is-light" role="button">Nevermind</a>
        
      </form>
    </div>
  </div>
</div>
</div>
</div>
  {% endblock %}

training_area/templates/training_area/coach/dashboard.html
{% extends 'navbar.html' %}
<script>
{% block jquery %}

var pk = 0;

$(".showModal").click(function() {
  event.preventDefault();
  pk = $(this).attr('key');
  console.log(pk);

  $(".modal").addClass("is-active");
});

$(".delete").click(function() {
   $(".modal").removeClass("is-active");
});

$(".no").click(function() {
   $(".modal").removeClass("is-active");
});

$(".yes").click(function() {
  console.log(pk);
   $.ajax({
        url: "/coach/ajax/remove_athlete/",
        type: "POST",
        data: {
          csrfmiddlewaretoken: $("input[name='csrfmiddlewaretoken']").val(),
          'pk': pk,
        },
        success: function (data) {
          console.log(data)
          location.reload();
        }
      });
   $(".modal").removeClass("is-active");
});

{% endblock %}
</script>

{% block content %}


<section class="hero is-dark welcome is-small">
                    <div class="hero-body">
                        <div class="container">
                            <h1 class="title">
                                Hello, Coach <u><a href="{% url 'app:profile_view' slug=request.user %}">{{request.user.first_name}}</a></u>
                            </h1>
                            <h2 class="subtitle">
                                Welcome To Your Dashboard!
                            </h2>


                              <!--<a class="button" href = "{% url 'athlete:search_coach' %}">Find Coach!</a>-->


                        </div>
                    </div>
</section>


<div class = "container has-background-dark">
  <section class="section">
  <div class = "container is-fluid">
  <div class="columns has-background-dark">
    <div class="column is-5">
      <div class="card is-fluid">
        <header class="card-header">
            <p class="card-header-title">
                  Existing Athletes
            </p>
            <a href="#" class="card-header-icon" aria-label="more options">
            <span class="icon">
            </span>
            </a>
        </header>
        <div class="card-table">
          <div class="content">
            <table class="table is-fullwidth is-striped">
              <thead>
                <tr>
                  <th>Athlete</th>
                  <th>Actions</th>
                </tr>
              </thead>
              <tbody>
                {% if available_athletes %}
                {% csrf_token %}
                  {%  for athlete in available_athletes  %}

                    <tr>
                      <td>{{athlete.user}}</td>

                          <td><a href="{% url 'app:profile_view' slug=athlete.user %}"><i class="fas fa-eye"></i></a>
                          <a href="{% url 'app:log_view' pk=athlete.pk %}"><i class="fas fa-dumbbell"></i></a>

                          <span class="icon has-text-danger"><i class="fas fa-times is-danger showModal" key="{{athlete.pk}}" name="showModal"></i></span>
                          <div class="modal" >
                    <div class="modal-background"></div>
                      <div class="modal-card">
                        <header class="modal-card-head  has-background-danger">
                          <p class="modal-card-title has-text-white">Confirm Athlete Removal</p>
                        </header>
                        <section class="modal-card-body" >
                          <strong>You will lose all information relating to this athlete! Are you sure you want to remove?</strong>
                        </section>
                        <footer class="modal-card-foot">
                          <button class="button yes is-success" key="{{athlete.pk}}">Yes, I'm sure</button>
                          <button class="button no">Nope!</button>
                        </footer>
                      </div>
                    </div>
                          </td>

                    </tr>
                  {% endfor %}
                  {% else %}
                    <tr>
                      <td width="5%"><i class="fas fa-exclamation-triangle"></i></i></td>
                      <td>You have no athletes yet!</td>
                    </tr>
                  {% endif %}
                </tbody>
              </table>
            </div>
          </div>
          <!--<footer class="card-footer">
            <a href="#" class="card-footer-item">View All</a>
          </footer>-->
        </div>
      </div>
      <div class = "column is-3 ">
        <div class = "box">

          <p class = "title is-size-5 has-text-centered all-events">Upcoming Events</p>

          <table class="table is-fullwidth is-striped is-hoverable">
            <thead>
              <tr>
                <th style="text-align: center;">Dates</th>
                <th style="text-align: center;">Event</th>
              </tr>
            </thead>
            <tbody>
              {% for day, value in calendar.items %}
              <tr>
                <td class = "subtitle is-size-7">{{value.0.day}}/{{value.0.month}}-{{value.1.day}}/{{value.1.month}}</td>
                <td class = "subtitle is-size-7">{{value.2}} {{day}}</td>
              </tr>
              {% endfor %}
            </tbody>


        </table>



        </div>
      </div>
      <div class = "column is-3">
        <div class = "box">

          <p class = "title is-size-5 has-text-centered all-events">Notifications</p>

          <table class="table is-fullwidth is-striped is-hoverable">
            <thead>
              <tr>
                <th></th>
                <th></th>
                <th></th>
              </tr>
            </thead>

            <tbody>

              {% for message in notif %}
              <tr>
                <td class = "subtitle is-size-7">{{message.created_at}}</td>
                {% autoescape off %}
                <td class = "subtitle is-size-7">{{message.title}}</td>
                {% endautoescape %}
                <td><a class = "button is-size-7 is-danger" href="{% url 'app:delete_notif' notif_id=message.pk %}"><i class="fas fa-trash-alt"></i></a></td>
              </tr>
              {% endfor %}
            </tbody>


        </table>
        {% if notif %}
        <div class="buttons has-addons is-centered">
          <span class="button is-small is-danger"><a href="{% url 'app:delete_all_notif' %}">Delete All</a></span>
        </div>
        {% endif %}


        </div>
      </div>

    </div>
  </div>
    </section>

  </div>



{% endblock %}

training_area/templates/training_area/coach/workout_edit_form.html
 {% extends 'navbar.html' %}
 {% load bulma_tags %}

 {% block content %}

 <div class="container section">

  <div class="column is-half is-offset-one-quarter">
<form method="post" novalidate>

    {% csrf_token %}
    

      <a class="is-medium">{{ form.workout_name|bulma }}</a>
   

    <button type="submit" class="button is-success is-small">Save changes</button>

</form>

</div>
</div>
{% endblock %}